services:

  postgresql-server:
    image: postgres:16.4-bullseye    
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data      
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      # - ./local_pgsql_conf:/etc/postgresql/conf.d # เพิ่ม volume สำหรับไฟล์ config
    ports:
      - "5432:5432"    
    networks:
      link:
        ipv4_address: 172.23.0.4

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:trunk-ubuntu
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
      # - ./local_zabbix_conf:/etc/zabbix # เพิ่ม volume สำหรับไฟล์ config
    networks:
      link:
        ipv4_address: 172.23.0.5

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:trunk-ubuntu
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_FRONTEND_PORT}:8080"
    volumes:
      - zabbix-web-data:/usr/share/zabbix
      # - ./local_web_conf:/etc/nginx/conf.d # เพิ่ม volume สำหรับไฟล์ config Nginx
    networks:
      link:
        ipv4_address: 172.23.0.6

  zabbix-agent:
    image: zabbix/zabbix-agent:trunk-ubuntu
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    # volumes:
    #   - ./local_agent_conf:/etc/zabbix/zabbix_agentd.conf # เพิ่ม volume สำหรับไฟล์ config agent
    networks:
      link:
        ipv4_address: 172.23.0.7

networks:
  link:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
